main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_html, show_json, show_json_by_id, show_xml, show_xml_by_id
from main.views import register, login_user, logout_user, adjust_amount, decrease_amount, delete_item
from main.views import get_item_json, create_ajax
from main.views import create_product_flutter, show_json_by_user, show_json_by_username

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('html', show_html, name='show_html'),
    path('xml', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json-by-user/', show_json_by_user, name='show_json_by_user'),
    path('json-by-username/<str:username>/', show_json_by_username, name='show_json_by_username'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('adjust-amount/<int:id>/<int:num>/', adjust_amount, name='adjust_amount'),
    path('decrease-amount/<int:id>/<int:num>/', decrease_amount, name='decrease_amount'),
    path('delete-item/<int:id>/', delete_item, name='delete_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', create_ajax, name='create_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

sentimental_sylladex/urls.py
from django.urls import path, include
"""
URL configuration for sentimental_sylladex project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField(default=0)
    description = models.TextField(default="")

# Extending :)
# class Employee(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     department = models.CharField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
import json
from django.shortcuts import render, redirect
from main.models import Item
from django.http import HttpResponseNotFound, HttpResponseRedirect, HttpResponse, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    context = {
        'app_name': 'The Sentimental Sylladex',
        'name': request.user.username,
        'pbp_class' : 'PBP E',
        'last_login': request.COOKIES['last_login'],
    }

    items = Item.objects.filter(user=request.user) # changed .values()
    amounts = Item.objects.filter(user=request.user).values_list('amount')
    amount_total = 0
    for amount in amounts:
        amount_total += int(amount[0])
    
    context['amount_total'] = amount_total
    context['items'] = items

    return render(request, "main.html", context)

def create_item(request):
    context = { 'app_name': 'The Sentimental Sylladex' }

    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context['form'] = form
    return render(request, "create_item.html", context)

def show_html(request):
    try:
        dataset = Item.objects.all()

        html_render = ""

        for data in dataset:
            html_render += f"""
            <p>Name: {data.name}</p>
            <p>Amount: {data.amount}</p>
            <p>Description: {data.description}</p>
            
            <hr>
            """

        return HttpResponse(html_render)
    
    except Item.DoesNotExist:
        return HttpResponse("There are no items in your Sylladex right now.")

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

# def show_json_by_user(request):
#     data = Item.objects.filter(user=request.user)
#     return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_user(request):
    # Check if the user is authenticated before filtering by user
    if request.user.is_authenticated:
        user_id = request.user.id  # Fetch the user's ID
        data = Item.objects.filter(user_id=user_id)  # Filter items by user ID
        serialized_data = serializers.serialize('json', data)
        return HttpResponse(serialized_data, content_type='application/json')
    else:
        # Handle the case when the user is not authenticated
        return HttpResponse("User is not authenticated", status=401)
    
def show_json_by_username(request, username):
    user = User.objects.get(username=username)
    data = Item.objects.filter(user=user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def adjust_amount(request, id, num):
    dataset = Item.objects.filter(pk=id)

    for data in dataset:
        data.amount += num
        data.save()

    return redirect('main:show_main')

def decrease_amount(request, id, num):
    dataset = Item.objects.filter(pk=id)

    for data in dataset:
        if ((data.amount - num) <= 0):
            data.delete()
        else:
            data.amount -= num
            data.save()

    return redirect('main:show_main')

def delete_item(request, id):
    dataset = Item.objects.filter(pk=id)

    for data in dataset:
        data.delete()
    
    return redirect('main:show_main')

def get_item_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def create_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Item(name=name, amount=amount, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block meta %}
    <title>Add Item</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% endblock meta %}

{% block content %}
<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg fixed-top shadow" style="background-color: #57b8a8;">
        <div class="container-fluid">
            <a class="navbar-brand" style="color: white; font-size: 28px; font-weight: bold;" href="#">
                {{ app_name }}
            </a>
            <a href="{% url 'main:show_main' %}">
                <button class="button button1">Back</button>
            </a>
        </div>
    </nav>
    <!-- Navbar -->
  </header>

<div class="container-fluid">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="col-md-6">
            <div>
                <h1>Add New Item</h1>
                <p>Tell us what you want to put into your Sentimental Sylladex!</p>
            </div>
            <form method="POST">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td>
                            <input type="submit" value="Add Item"/>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>

    <!-- Kermit -->
    <!-- <img src="https://static.wikia.nocookie.net/villainsfanon/images/5/53/CMB_Kermit.png/" class="fix" width="220" height="auto" style="right: 0%;"/> -->

    <br/>

<!-- Footer -->
<footer
class="text-center text-lg-start text-dark"
style="background-color: #ECEFF1"
>
<section
   class="d-flex justify-content-between p-4 text-white"
   style="background-color: #57b8a8"
   >
<div class="me-auto">
<span>A collection of items from the old, the new, and the eternal. The Kermit aesthetic was decided on a whim. Please don't ask why, I don't know either.</span>
</div>
</section>

<!-- Copyright -->
<div
class="text-center p-3"
style="background-color: #57b8a8; color: white;"
>
© 2023 Copyright
</div>
<!-- Copyright -->

</footer>
<!-- Footer -->

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% endblock meta %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="col-md-6">
            <div>
                <h1>Log In</h1>
                <p>Welcome back to your Sentimental Sylladex.</p>
            </div>
            <form method="POST" action="">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username:</label>
                    <input type="text" name="username" id="username" placeholder="Username" class="form-control">
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" name="password" id="password" placeholder="Password" class="form-control">
                </div>
                <input class="btn btn-primary" type="submit" value="Login">
            </form>
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <br/>
            <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg fixed-top shadow" style="background-color: #57b8a8;">
        <div class="container-fluid">
            <a class="navbar-brand" style="color: white; font-size: 28px; font-weight: bold;" href="#">
                {{ app_name }}
            </a>
            <a href="{% url 'main:logout' %}">
                <button class="button button1">Logout</button>
            </a>
        </div>
    </nav>
    <!-- Navbar -->
  
    <!-- Background image -->
    <div
      class="jumbotron p-5 text-center bg-image"
      style="
        background-image: url('https://imgix.bustle.com/inverse/ff/19/fc/02/501c/4a8c/9fb5/0a93d3c05cb7.jpeg?w=1200&h=630&fit=crop&crop=faces&fm=jpg');
        height: 400px;
        margin-top: 58px;
      "
    >
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="text-white">
            <h1 class="mb-3">Hello, {{ name }}!</h1>
            <h4 class="mb-3">Welcome back to your {{ pbp_class }} Sentimental Sylladex.</h4>
            </div>
        </div>
    </div>
    <!-- Background image -->

  </header>
    
    <!-- <div class="inventory">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Amount</th>
                    <th>Description</th>
                    <th>Increase Item</th>
                    <th>Decrease Item</th>
                    <th>Delete Item</th>
                    
                </tr>
            </thead>

            <h3> Item Total: {{ amount_total }} </h3>
            
            <tbody class="table-group-divider">
                {% for thing in items %}
                <tr>
                    <td style="white-space: nowrap;">{{ thing.name }}</td>
                    <td style="white-space: nowrap;">{{ thing.amount }}</td>
                    <td style="width: stretch;">{{ thing.description }}</td>
                    <td>
                        <a href="/adjust-amount/{{thing.pk}}/1/">
                            <button class="button button1" id="adjust-btn" type="submit">+1</button>
                        </a>
                    </td>
                    
                    <td>
                        <a href="/decrease-amount/{{thing.pk}}/1/">
                            <button class="button button1" id="adjust-btn" type="submit">-1</button>
                        </a>
                    </td>
                    
                    <td>
                        <a href="/delete-item/{{thing.pk}}/">
                            <button class="button button1" id="adjust-btn" type="submit">Delete</button>
                        </a>
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
            <caption>Sesi terakhir login: {{ last_login }}</caption>

        </table>

        <center>
            <a class="btn btn-outline-dark btn-lg" href="{% url 'main:create_item' %}" role="button">Add New Item</a>
        </center>

        <br />
        <br />

    </div> -->


    <h3 id="total_items" style="margin: 2.5%; margin-top: 3.5%;"> Item Total: {{ amount_total }} </h3>

    <div id="all_items" class="inventory row row-cols-1 row-cols-md-3 g-4"></div>

    <center>
        <button type="button" class="btn btn-outline-dark btn-lg" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin: 2.5%;">Add Item</button>
    </center>

    <p style="margin: 2.5%;">Sesi terakhir login: {{ last_login }}</p>

    

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Item</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Amount:</label>
                            <input type="number" class="form-control" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Kermit -->
    <!-- <img src="https://www.seekpng.com/png/full/67-677599_kermit-the-frog.png" class="fix" width="150" height="auto"/> -->

    <!-- Footer -->
    <footer
            class="text-center text-lg-start text-dark"
            style="background-color: #ECEFF1"
            >
      <section
               class="d-flex justify-content-between p-4 text-white"
               style="background-color: #57b8a8"
               >
        <div class="me-auto">
          <span>A collection of items from the old, the new, and the eternal. The Kermit aesthetic was decided on a whim. Please don't ask why, I don't know either.</span>
        </div>
      </section>

      <!-- Copyright -->
      <div
           class="text-center p-3"
           style="background-color: #57b8a8; color: white;"
           >
        © 2023 Copyright
      </div>
      <!-- Copyright -->

    </footer>
    <!-- Footer -->


    <script>
        async function getProducts() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
        }

        const imageArr = [
        'https://i.pinimg.com/originals/45/a2/86/45a286f052a589374edc6205957a49af.jpg',
        'https://i.pinimg.com/originals/4f/3f/ed/4f3fed9d55f6a7ee5aebd45dc32d81e1.jpg',
        'https://bagbytransfer.com/wp-content/uploads/movie-themuppets.jpg',
        'https://kingoflimericks.com/wp-content/uploads/2019/04/Kermit-and-the-Mythology-of-Muppets.jpg',
        'https://i.pinimg.com/736x/a5/af/3c/a5af3c234923c9c1151113f2bc5a7ac0--kermit-the-frog-the-muppets.jpg',
        'https://toughpigs.com/wp-content/uploads/2016/10/grey7.jpg',
        ];

        async function refreshProducts() {
            document.getElementById("all_items").innerHTML = ""
            const products = await getProducts()
            let htmlString = ``
            let total = 0
            var count = 0;
            let totalString = `Item Total: `
            products.forEach((item) => {
                total += item.fields.amount
                totalString = `Item Total: ${total}`
                htmlString += `\n
                <div class="col">
                    <div class="card">
                        <img src="${imageArr[count]}" class="card-img-top"
                        alt="Kermeet" />
                        <div class="card-body">
                            <h5 class="card-title" style="color: #57b8a8;">${item.fields.name}</h5>
                            <p class="card-text">
                                Amount: ${item.fields.amount}
                            </p>
                            <p class="card-text">
                            ${item.fields.description}
                            </p>
                            <a href="/adjust-amount/${item.pk}/1/">
                                <button class="button button1" id="adjust-btn" type="submit">+1</button>
                            </a>
                            <a href="/decrease-amount/${item.pk}/1/">
                                <button class="button button1" id="adjust-btn" type="submit">-1</button>
                            </a>
                            <a href="/delete-item/${item.pk}/">
                                <button class="button button1" id="adjust-btn" type="submit">Delete</button>
                            </a>
                        </div>
                    </div>
                </div>\n`

                if (count < 5) {
                    count++;
                } else {
                    count = 0;
                }
            })
            
            document.getElementById("all_items").innerHTML = htmlString
            document.getElementById("total_items").innerHTML = totalString
        }

        refreshProducts()

        function addProduct() {
            fetch("{% url 'main:create_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }

        document.getElementById("button_add").onclick = addProduct

    </script>
    
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% endblock meta %}

{% block content %}  

<div class="container-fluid">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="col-md-6">
            <div>
                <h1>Register</h1>
                <p>Have you registered your sylladex yet?</p>
            </div>
            <form method="POST">
                {% csrf_token %}
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>
            </form>
            
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <br/>
        </div>
    </div>
</div>

{% endblock content %}